Document: keybase
Title: Debian keybase Manual
Author: <insert document author here>
Abstract: This manual describes what keybase is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/keybase/keybase.sgml.gz

Format: postscript
Files: /usr/share/doc/keybase/keybase.ps.gz

Format: text
Files: /usr/share/doc/keybase/keybase.text.gz

Format: HTML
Index: /usr/share/doc/keybase/html/index.html
Files: /usr/share/doc/keybase/html/*.html
